---

- name: Creat init.groovy.d directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    state: directory

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Copy Jenkins plugins
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}/plugins"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  with_fileglob: "plugins/*.hpi"

- name: restart jenkins
  service:
    name: jenkins
    state: restarted