---

- name: Uninstall packages
  dnf:
    name: 
      - jenkins
      - java-11-openjdk
    state: absent

- name: Remove offline jenkins repo
  file: 
    path: "{{ jenkins_offline_repo_path }}"
    state: absent

- name: Remove jenkins repo to yum repos
  file:
    path: /etc/yum.repos.d/jenkins.repo
    state: absent

- name: Jenkins files
  file:
    path: "{{ item }}"
    state: absent
  with_items: 
    - /var/lib/jenkins/
    - /var/cache/jenkins/
