---

- name: Install Jenkins
  hosts: localhost
  connection: local
  become: true
  roles:
    - { role: install, tags: install }
    - { role: uninstall, tags: uninstall }
  vars_files:
    - vars/main.yml